server {
    listen 8080;
    server_name localhost;
    root /usr/share/nginx/html;

    location /atlas {
        alias /usr/share/nginx/html/atlas;
        try_files $uri $uri/ /atlas/index.html;
    }
}
